-- ÍNDICES DE PEDIDO
EXPLAIN ANALYZE SELECT * FROM PEDIDO WHERE id_cliente = 1;

CREATE INDEX idx_pedido_cliente ON PEDIDO(id_cliente);
CREATE INDEX idx_pedido_estado ON PEDIDO(estado);

EXPLAIN ANALYZE SELECT * FROM PEDIDO WHERE id_cliente = 1;

-- INDICES DE PRODUCTO
EXPLAIN ANALYZE SELECT * FROM PRODUCTO WHERE nombre LIKE 'C%';

CREATE INDEX idx_producto_nombre ON PRODUCTO(nombre);
CREATE INDEX idx_producto_stock ON PRODUCTO(stock);

EXPLAIN ANALYZE SELECT * FROM PRODUCTO WHERE nombre LIKE 'C%'; 
